# trainer
dataset: celeba
num_epochs: 20000
batch_size: 64
learning_rate: 0.0001
run_train: True
exp_name: celeba_train_v2_depth_mask
exp_path: experiments/celeba_train
chk_path: models/celeba_train

img_size: 64

# light configs
lambda_p: 0.5
lambda_f: 1.0

# network versions
depth_v: depth_v0
alb_v: alb_v0
light_v: light_v0
view_v: view_v0

use_gt_depth: false
use_conf: true
write_logs: true


# visualize option
plot_size: 256
fig_plot_epoch: 15 
plot_num: 32


# chkpt option
save_epoch: 1000


# load saved option
load_chk: false
load_path: experiments/celeba_train/celeba_train_v0_05_21__13_29/models/best.pt